### PR TITLE
[#439] Fix README file

### LINKED ISSUE #439: The title in the README is (logically) incorrect
Just a very very minor heads up, the title in the README reads:

**TCR - Test && (Commit || Revert) application**

While it should have been

**TCR - (Test && Commit || Revert) application**

Feel free to ignore this one :)

### PR DESCRIPTION
**Pull request by Dainerx**
# Description:
Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. List any dependencies 
that are required for this change.

Fixes #439

## Type of change
Please tick the appropriate option using [x]

- [x] Bug fix
- [ ] New feature

# Checklist:
Please tick the appropriate options using [x]

- [ ] My PR includes tests that cover my code changes.
- [ ] Lint and formatter run with no errors
- [ ] All new and old tests are passing

### CODE REVIEW

**Comment by mengdaming** [comment]
Hi @Dainerx,

Before we can merge your PR, can you review and sign Murex CLA as explained [here](https://github.com/murex/contribution)?

Thanks!

**Review by philou — CHANGES_REQUESTED** [review]
Revert is supposed to run if test fail, not if commit fails. Paren are good as they are

**Comment by mengdaming** [comment]
Ok, let's close this PR and related issue.

@Dainerx my previous comment about reviewing and signing Murex CLA is still valid if you're still planning to contribute to other TCR issues 😃

**Comment by mengdaming** [comment]
issue #439 is not relevant

**Comment by philou** [comment]
My bad. I had read the diff without color highlighting! We should indeed be merging this PR!

**Comment by Dainerx** [comment]
So are we opening this PR?

**Pull request closed without merging**
